# Generated by Django 4.2.28 on 2026-02-20 20:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AtivoB3',
            fields=[
                ('ticker', models.CharField(help_text='Instrumento financeiro (chave primária)', max_length=200, primary_key=True, serialize=False, verbose_name='Ticker')),
                ('ativo_objeto', models.CharField(db_index=True, max_length=50, verbose_name='Ativo Objeto')),
                ('descricao_ativo', models.CharField(blank=True, max_length=500, verbose_name='Descrição do Ativo')),
                ('segmento', models.CharField(blank=True, max_length=100, verbose_name='Segmento')),
                ('mercado', models.CharField(blank=True, max_length=100, verbose_name='Mercado')),
                ('categoria', models.CharField(blank=True, max_length=100, verbose_name='Categoria')),
                ('data_expiracao', models.DateField(blank=True, null=True, verbose_name='Data de Expiração')),
                ('data_inicio_negocio', models.DateField(blank=True, null=True, verbose_name='Data Início Negócio')),
                ('data_fim_negocio', models.DateField(blank=True, null=True, verbose_name='Data Fim Negócio')),
                ('data_inicio_evento_corp', models.DateField(blank=True, null=True, verbose_name='Data Início Evento Corporativo')),
                ('codigo_isin', models.CharField(blank=True, max_length=20, verbose_name='Código ISIN')),
                ('codigo_cfi', models.CharField(blank=True, max_length=10, verbose_name='Código CFI')),
                ('codigo_especificacao', models.CharField(blank=True, max_length=50, verbose_name='Código de Especificação')),
                ('id_distribuicao', models.IntegerField(blank=True, null=True, verbose_name='Identificador Distribuição')),
                ('tipo_opcao', models.CharField(blank=True, max_length=50, verbose_name='Tipo de Opção')),
                ('preco_exercicio', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Preço de Exercício')),
                ('estilo_opcao', models.CharField(blank=True, max_length=50, verbose_name='Estilo de Opção')),
                ('tamanho_lote', models.IntegerField(blank=True, null=True, verbose_name='Tamanho de Lote')),
                ('moeda_negociada', models.CharField(blank=True, max_length=10, verbose_name='Moeda Negociada')),
                ('tipo_entrega', models.CharField(blank=True, max_length=50, verbose_name='Tipo de Entrega')),
                ('capital_social', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Capital Social')),
                ('ind_premio_antecipado', models.BooleanField(default=False, verbose_name='Ind. Prêmio Antecipado')),
                ('exercicio_automatico', models.BooleanField(default=False, verbose_name='Exercício Automático')),
                ('fator_preco', models.IntegerField(blank=True, null=True, verbose_name='Fator de Preço')),
                ('dias_liquidacao', models.IntegerField(blank=True, null=True, verbose_name='Dias para Liquidação')),
                ('tipo_serie', models.CharField(blank=True, max_length=50, verbose_name='Tipo de Série')),
                ('ind_protecao', models.CharField(blank=True, max_length=50, verbose_name='Indicador de Proteção')),
                ('nivel_governanca', models.CharField(blank=True, max_length=50, verbose_name='Nível Governança')),
                ('tipo_tratamento_custodia', models.CharField(blank=True, max_length=50, verbose_name='Tipo Tratamento Custódia')),
                ('nome_instituicao', models.CharField(blank=True, max_length=200, verbose_name='Nome da Instituição')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Ativo B3',
                'verbose_name_plural': 'Ativos B3',
                'ordering': ['ativo_objeto', 'ticker'],
                'indexes': [models.Index(fields=['ativo_objeto', 'data_expiracao'], name='core_ativob_ativo_o_de97f6_idx'), models.Index(fields=['tipo_opcao', 'preco_exercicio'], name='core_ativob_tipo_op_21b491_idx')],
            },
        ),
    ]
