# Generated by Django 6.0.2 on 2026-02-21 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativob3',
            name='codigo_isin',
            field=models.CharField(help_text='Identificador único universal do ativo', max_length=20, primary_key=True, serialize=False, verbose_name='Código ISIN'),
        ),
        migrations.AlterField(
            model_name='ativob3',
            name='ticker',
            field=models.CharField(db_index=True, help_text='Instrumento financeiro (ex: PETRL280)', max_length=50, verbose_name='Ticker'),
        ),
    ]
