# Generated by Django 6.0.2 on 2026-02-21 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_ativob3_codigo_isin_alter_ativob3_ticker'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoImportacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_importacao', models.DateTimeField(auto_now_add=True)),
                ('arquivo_nome', models.CharField(max_length=255)),
                ('novos', models.IntegerField(default=0)),
                ('atualizados', models.IntegerField(default=0)),
                ('sem_alteracao', models.IntegerField(default=0)),
                ('detalhes', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-data_importacao'],
            },
        ),
    ]
