# Generated by Django 6.0.2 on 2026-02-21 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_historicoimportacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtivoMonitorado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(help_text='Ex: PETR4, VALE3', max_length=10, unique=True)),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('ativo_no_dashboard', models.BooleanField(default=True, help_text='Se desmarcado, ignora na próxima importação')),
            ],
            options={
                'verbose_name': 'Ativos Monitorados',
            },
        ),
    ]
