# Generated by Django 6.0.2 on 2026-02-21 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_acessolog'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoPreco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pregao', models.DateField()),
                ('abertura', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('maximo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('minimo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('fechamento', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ajuste', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('quantidade_negocios', models.IntegerField(default=0)),
                ('volume_financeiro', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('ativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos', to='core.ativob3')),
            ],
            options={
                'verbose_name': 'Histórico de Preço',
                'verbose_name_plural': 'Históricos de Preços',
                'unique_together': {('ativo', 'data_pregao')},
            },
        ),
    ]
